### ISSUE TITLE
Examples do not work on Ubuntu 13.10 with Node.js 0.10.26

### ISSUE THREAD

**Issue by richsad** [TooTallNate/node-speaker#26]
Hi. I can't get anything to work with this package including the examples that come with it. The sine.js example yields:
enerating a 440hz sine wave for 2 seconds

/home/rich/node/testalsa/node_modules/speaker/examples/sine.js:54
  fn(null, buf);
  ^
TypeError: undefined is not a function
    at Readable.read [as _read](/home/rich/node/testalsa/node_modules/speaker/examples/sine.js:54:3)
    at Readable.read (_stream_readable.js:320:10)
    at Readable.on (_stream_readable.js:701:14)
    at Readable.pipe (_stream_readable.js:556:10)
    at Object.<anonymous> (/home/rich/node/testalsa/node_modules/speaker/examples/sine.js:30:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

The stdin.js example gives the following error after I type a few keys:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write() failed: 4
    at afterWrite (/home/rich/node/testalsa/node_modules/speaker/index.js:204:12)
r

It is totally possible this is user error in some way. FWIW I haven't gotten any node.js audio module except for node-lame to work. I do have alsa on this Ubuntu install and audio applications like audacious can record and playback audio. My audio hardware looks like this (aplay -l):

card 0: PCH [HDA Intel PCH], device 0: ALC283 Analog [ALC283 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 3: ID 2882 Digital [ID 2882 Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
