### ISSUE TITLE
unable to build on 0.11.3

### ISSUE THREAD

**Issue by skyblue** [TooTallNate/node-speaker#25]
```
In file included from ../src/binding.cc:6:
../src/node_pointer.h:23:9: error: unexpected namespace name 'Buffer': expected expression
  node::Buffer *buf = node::Buffer::New((char *)ptr, length, wrap_pointer_cb, user_data);
        ^
../src/node_pointer.h:23:17: error: use of undeclared identifier 'buf'
  node::Buffer *buf = node::Buffer::New((char *)ptr, length, wrap_pointer_cb, user_data);
                ^
../src/node_pointer.h:24:10: error: use of undeclared identifier 'buf'
  return buf->handle_;
         ^
../src/binding.cc:17:3: error: unknown type name 'uv_work_t'
  uv_work_t req;
```
